/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/genres/': RouteRecordInfo<'/admin/genres/', '/admin/genres', Record<never, never>, Record<never, never>>,
    '/admin/genres/add/': RouteRecordInfo<'/admin/genres/add/', '/admin/genres/add', Record<never, never>, Record<never, never>>,
    '/admin/songs/': RouteRecordInfo<'/admin/songs/', '/admin/songs', Record<never, never>, Record<never, never>>,
    '/admin/songs/add/': RouteRecordInfo<'/admin/songs/add/', '/admin/songs/add', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/callback/': RouteRecordInfo<'/auth/callback/', '/auth/callback', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register/': RouteRecordInfo<'/auth/register/', '/auth/register', Record<never, never>, Record<never, never>>,
    '/permission-denied': RouteRecordInfo<'/permission-denied', '/permission-denied', Record<never, never>, Record<never, never>>,
    '/player': RouteRecordInfo<'/player', '/player', Record<never, never>, Record<never, never>>,
    '/player/': RouteRecordInfo<'/player/', '/player', Record<never, never>, Record<never, never>>,
    '/player/lib': RouteRecordInfo<'/player/lib', '/player/lib', Record<never, never>, Record<never, never>>,
    '/player/lib/': RouteRecordInfo<'/player/lib/', '/player/lib', Record<never, never>, Record<never, never>>,
    '/player/lib/albums/': RouteRecordInfo<'/player/lib/albums/', '/player/lib/albums', Record<never, never>, Record<never, never>>,
    '/player/lib/artists/': RouteRecordInfo<'/player/lib/artists/', '/player/lib/artists', Record<never, never>, Record<never, never>>,
    '/player/lib/playlists/': RouteRecordInfo<'/player/lib/playlists/', '/player/lib/playlists', Record<never, never>, Record<never, never>>,
    '/player/lib/uploads/': RouteRecordInfo<'/player/lib/uploads/', '/player/lib/uploads', Record<never, never>, Record<never, never>>,
    '/player/search/': RouteRecordInfo<'/player/search/', '/player/search', Record<never, never>, Record<never, never>>,
    '/player/settings/': RouteRecordInfo<'/player/settings/', '/player/settings', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
  }
}
