services:
  app:
    build: .
    volumes:
      - .:/app
      - ./html/api/content:/var/www/html/api/content
    ports:
      - '80:80'
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
    depends_on:
      - database

volumes:
  db-data:
